### ISSUE TITLE
[Feature Suggestion] Publishing to OpenVSX

### ISSUE THREAD

**Issue by AZMCode** [jurassiscripts/vscode-velociraptor#1]
I was wondering whether this plugin could also be released to open-vsx.org, to allow [codium](https://vscodium.com/) users (like myself) easy access to the plugin.

**Comment by umbopepato** [comment]
Hey @AZMCode, thanks for the suggestion! The extension is now available on open-vsk.org, I'll leave you to close this if it works 🙂

**Comment by AZMCode** [comment]
It works like a charm. Thanks!
